name: Publish Docker image
on:
    push:
        branches:
          - master
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          tags: |
            jayvirrathi/nodejs:latest
            jayvirrathi/nodejs:v3.0.0
            ghcr.io/jayvirrathi/nodejs:latest
            ghcr.io/jayvirrathi/nodejs:v3.0.0
            docker.pkg.github.com/jayvirrathi/nodejs-docker-kubernetes/nodejs:latest
            docker.pkg.github.com/jayvirrathi/nodejs-docker-kubernetes/nodejs:v3.0.0
